### ISSUE TITLE
not working on m1 mac.

### ISSUE THREAD

**Issue by lustfeind** [cocktailpeanutlabs/openvoice#1]
not working on m1 mac.

Traceback (most recent call last):
  File "/Users/hoguriso/pinokio/api/openvoice.git/app/env/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/Users/hoguriso/pinokio/api/openvoice.git/app/env/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/hoguriso/pinokio/api/openvoice.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1548, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/hoguriso/pinokio/api/openvoice.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1329, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/hoguriso/pinokio/api/openvoice.git/app/env/lib/python3.10/site-packages/gradio/components/audio.py", line 212, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "/Users/hoguriso/pinokio/api/openvoice.git/app/env/lib/python3.10/site-packages/gradio/processing_utils.py", line 145, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "/Users/hoguriso/pinokio/api/openvoice.git/app/env/lib/python3.10/site-packages/pydub/audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 234

Output from ffmpeg/avlib:

ffmpeg version 6.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with clang version 16.0.6
  configuration: --prefix=/Users/runner/miniforge3/conda-bld/ffmpeg_1700971234251/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl --cc=arm64-apple-darwin20.0.0-clang --cxx=arm64-apple-darwin20.0.0-clang++ --nm=arm64-apple-darwin20.0.0-nm --ar=arm64-apple-darwin20.0.0-ar --disable-doc --disable-openssl --enable-demuxer=dash --enable-hardcoded-tables --enable-libfreetype --enable-libfontconfig --enable-libopenh264 --enable-libdav1d --enable-cross-compile --arch=arm64 --target-os=darwin --cross-prefix=arm64-apple-darwin20.0.0- --host-cc=/Users/runner/miniforge3/conda-bld/ffmpeg_1700971234251/_build_env/bin/x86_64-apple-darwin13.4.0-clang --enable-neon --enable-gnutls --enable-libmp3lame --enable-libvpx --enable-libass --enable-pthreads --enable-gpl --enable-libx264 --enable-libx265 --enable-libaom --enable-libsvtav1 --enable-libxml2 --enable-pic --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libopus --pkg-config=/Users/runner/miniforge3/conda-bld/ffmpeg_1700971234251/_build_env/bin/pkg-config
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[mp3 @ 0x132005ee0] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 0x132005ee0] Failed to read frame size: Could not seek to 1154.
[in#0 @ 0x132005dd0] Error opening input: Invalid argument
Error opening input file /var/folders/hn/vqbkt09n2351q4s6vpn841980000gn/T/gradio/de3fa2bf97b502c204a60bf15ca439cfcba7911e/speaker0.mp3.
Error opening input files: Invalid argument

**Comment by alfi4000** [comment]
Yeah that is because the most applications are build on NVIDIA GPUs and Macs who have a M1 not an NVIDIA graphic card in your case, you might should consider using for that  kind of application a Virtual Machine!

**Comment by alfi4000** [comment]
Virtual box or something like that I am not a professional in that I just bought a server and added a NVIDIA card so I don’t have those problems!

**Comment by ar4angeel** [comment]
![изображение](https://github.com/cocktailpeanutlabs/openvoice/assets/82732181/4a86584e-2853-43ab-83a8-841e32da8d3a)
openvoice not download jn rtx 4060. take download button and next step was white window
